[project]
name = "bs3d-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.86.5",
]
[tool.flet]
app_title = "BS3D-Simulator"

[tool.flet.windows]
product_name = "BS3D-Simulator"
product_version = "1.0.0"

[tool.flet.linux]
desktop_flavor = "light"